- name: Installs the AD-Domain-Services feature
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present

- name: Sets up the AD controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"

- name: Reboot windows server
  win_reboot:
    pre_reboot_delay: 5

- name: list domain name
  win_command: nltest /dclist:"{{ ad_domain_name }}"
  register: result
      
- name: Print out domain result
  debug: 
    msg: "Result: {{ result }}"
