- name: install the Win OpenSSH service
  win_chocolatey:
    name: "{{ package_name }}"
    package_params: "{{ parameters }}"
    state: latest
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Enable {{ service_name }}
  win_service:
    name: "{{ service_name }}"
  register: result
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Print out service
  debug: 
    msg: "Result: {{ result }}"

- name: open port 22 for inbound SSH connections
  win_firewall_rule:
    name: Win32-OpenSSH inbound
    protocol: "{{ protocol_name }}"
    localport: "{{ local_port }}"
    direction: in
    action: allow
    state: present
    enabled: yes

